# Generated by Django 3.0.1 on 2019-12-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('profile_app', '0002_auto_20191231_0929'), ('profile_app', '0003_auto_20191231_0935'), ('profile_app', '0004_auto_20191231_0939')]

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='World',
            new_name='Gender',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Planet',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='world',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.Planet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.Species'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.Type'),
        ),
    ]
